Q1 : Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.


Vektorler tek satirli veya tek sutunlu matrislerdir ve matrislerin ozel bir cesididir.

Q2 : 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q3 : Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [6]:
matris=np.zeros((10,10), dtype = int)
matris

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Q4 : Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [7]:
matris=np.ones((10,10), dtype = float)
matris

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Q5 : Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [8]:
matris=np.full((10,10),9, dtype = int)
matris

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

Q6 : 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [10]:
matris=np.arange(5,25, 3) #0'dan 31'e kadar 3'er artarak dizi olusturma
matris

array([ 5,  8, 11, 14, 17, 20, 23])

Q7 : -1 ile 1 arasinda 30 adet Array olusturunuz.

In [12]:
matris=np.linspace(-1,1,30) 
matris

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

Q8 : 0 ile 30 arasinda 5x6’lik bir matris olusturun.


In [15]:
matris=np.random.normal(0,30,(5,6)) 
matris

array([[-56.21318141, -22.02620107,  46.73753823,  23.44434517,
         45.21756427, -11.38906813],
       [ -9.83494721, -30.08532165,  18.15919179, -12.86000047,
        -36.762211  ,   7.55724492],
       [ 19.39861052, -24.24666492, -18.64241907, -64.47135094,
        -38.00581716,   6.39715646],
       [ 10.30072186,  16.04578615,   5.89302287, -48.69163042,
          3.25846821,  21.74540165],
       [ 73.36097865,  -0.78954107,  25.45977881,  46.13845353,
        -36.965716  , -38.98298925]])

Q9 : Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

Q10 : 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; • eleman sayisini • boyut bilgisini/sayisini • satir X sutun bilgisini • veri tipini numpy metodlariyla yazdiriniz.

In [81]:
matris=np.random.normal(0,10,(5,10)) 
print( f" eleman sayisi : {matris.size}")
print( f" boyut bilgisi: {matris.ndim}")
print( f" boyut bilgisi : {matris.shape}")
print( f" veri tipi sayisi : {matris.dtype}")


 eleman sayisi : 50
 boyut bilgisi: 2
 boyut bilgisi : (5, 10)
 veri tipi sayisi : float64


Q11 : 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [32]:
matris=np.random.normal(0,10,(3,7)) 
matris

array([[ -8.6540897 ,  -5.34067868,   0.28084627,  -4.03745597,
          0.88682235,  -1.97242269,  -7.05413234],
       [-15.96485385,  -2.02815091,  -0.91185459,  11.38006373,
          2.98014789,  -6.4799644 ,   3.06935479],
       [-10.17349102,   1.4756834 ,  -0.1471539 ,  -0.34692603,
         -5.89234676,  11.32645336,  10.13526821]])

Q12: Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [35]:
b = np.arange(1,10)
b


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q 13: 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [51]:
a = np.random.randint(10, size = (10))
b = np.random.randint(10, size = (10))
c = np.random.randint(10, size = (10))
d = np.random.randint(10, size = (10))

In [56]:
matris=np.concatenate([a,b,c,d])
matris.reshape(4,10)

array([[9, 2, 2, 9, 9, 7, 2, 5, 6, 1],
       [9, 7, 9, 3, 7, 3, 1, 7, 2, 4],
       [5, 8, 1, 0, 0, 6, 0, 2, 0, 8],
       [7, 1, 0, 2, 5, 6, 2, 4, 8, 2]])

Q 14: 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [74]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [73]:
b = np.array([[7,8,9],
             [10,11,12]])

In [75]:
np.concatenate([a,b],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q 15 : Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

 axis=0 satiri , x eksenini , yatayi
 axis=1 sutunu , y eksenini , dikeyi temsil eder

Q 16 : Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [89]:
a = np.arange(4)                # 1x4 boyutunda arrayi 3x3 array ile birlestirmek istiyoruz
a = np.arange(9).reshape(3,3)   # 1x9 arrayi 2x3'e cevirebiliriz
b = np.array([[1,2,3],[4,4,4],[5,5,6]])    # bu durumda 3x3 ile dikey olarak birlestirebiliriz       
np.vstack((a, b))      # ayni boyuta getirip birlestirebiliriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [4, 4, 4],
       [5, 5, 6]])

In [90]:
x = np.array([1,2,3])                   # 1x3 ile
y = np.arange(9).reshape(3,3)           # 3x3 yatay olarak birlestirmek icin
z = np.hstack((x, y.reshape(9,)))       # ayni boyuta getirip (3x3 = 1x9) birlestirebiliriz
print("\n",z) 



 [1 2 3 0 1 2 3 4 5 6 7 8]


Q 17 : 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

In [91]:
liste = [1,2,3,4,5,6,7,8,9,10]
a,b,c,d,e = np.split(liste, [2,4,6,8])
a,b,c,d,e

(array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]))

Q 18 : Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [92]:
arr = np.random.randint(10, size=10)
arr.sort()
arr

array([1, 1, 1, 3, 4, 4, 7, 8, 8, 9])

Q 19 : 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [93]:
vek = np.random.randint(10, size=20)
print(vek)
split=[3,5,7]
print(vek[split])

[8 8 9 9 6 6 6 2 7 7 8 7 8 9 8 5 2 0 3 2]
[9 6 2]


Q 20 : 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [94]:
arr = np.random.randint(10, size=10)
print(arr)
arr[4]=99
print(arr)

[2 9 1 7 0 4 9 9 8 1]
[ 2  9  1  7 99  4  9  9  8  1]


Q 21 : “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

Answer: Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise köşegen yani "DIAGONAL matris" matris denir.

Kosegen uzerindeki elemanlarin toplamina Matris izi "Trace of Matrix" denir

Q 22 : 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [95]:
matris = np.eye(5,5)
print(matris)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [97]:
print(matris[[0,1,2,3,4],[0,1,2,3,4]])  

[1. 1. 1. 1. 1.]


In [100]:
for i in range (len(matris)):             
    print(matris[i,i])

1.0
1.0
1.0
1.0
1.0


Q 23 : 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [101]:
vektor = np.arange(10,20)
vektor[3:]

array([13, 14, 15, 16, 17, 18, 19])

Q 24 : 10X10 luk bir matris olusturunuz ve ; • 3.satir ve 5.sutuna ulasiniz. • 5.sutunun tum satirlarina ulasiniz. • Tum sutunlarin 2.satirlarina ulasiniz. • tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. • satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. • satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. • sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. • 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [102]:
matris = np.arange(100).reshape(10,10)
matris

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
matris[3,5]

35

In [105]:
matris[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [106]:
matris[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [107]:
matris[2:7,:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [108]:
matris[2:5,3:7]

array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46]])

In [109]:
matris[5:,:4]

array([[50, 51, 52, 53],
       [60, 61, 62, 63],
       [70, 71, 72, 73],
       [80, 81, 82, 83],
       [90, 91, 92, 93]])

In [110]:
matris[:,[3,6,9]]

array([[ 3,  6,  9],
       [13, 16, 19],
       [23, 26, 29],
       [33, 36, 39],
       [43, 46, 49],
       [53, 56, 59],
       [63, 66, 69],
       [73, 76, 79],
       [83, 86, 89],
       [93, 96, 99]])

In [113]:
matris[5,5]=1994

In [114]:
matris

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54, 1994,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

Q 25: 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin; • 20 den buyuk olan kac deger var. • 30’dan kucuk kac deger var • icerisinde 33 gecen kac deger var • olusturulan arrayin tum elemanlarini 5 ile carpin. • olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [116]:
matris = np.arange(0,50,5)
matris

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [117]:
np.sum(matris>20)

5

In [118]:
np.sum(matris<30)

6

In [120]:
np.sum(matris==33)

0

In [121]:
matris*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [123]:
matris%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

Q 26 : 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; • ortalamasini aliniz. • standart sapmasini aliniz. • varyansini aliniz. • median’ini aliniz. • en kucuk degeri bulunuz. • en buyuk degeri bulunuz. Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [125]:
matris=np.random.rand(1,50)
matris

array([[0.80364887, 0.15408956, 0.33889542, 0.81648334, 0.35867145,
        0.21219236, 0.57617431, 0.74833844, 0.06687243, 0.92240604,
        0.64428213, 0.78977621, 0.46425044, 0.94485768, 0.59708114,
        0.68237221, 0.52456106, 0.36759042, 0.10757879, 0.02229632,
        0.49263809, 0.45611647, 0.62510914, 0.19460669, 0.45543144,
        0.15191131, 0.95954523, 0.99000301, 0.2474172 , 0.29161078,
        0.48400066, 0.1747116 , 0.78265979, 0.68775821, 0.76949239,
        0.52743777, 0.24243663, 0.68923509, 0.46384481, 0.07323816,
        0.83956771, 0.76312992, 0.03174492, 0.45480116, 0.02634595,
        0.11011725, 0.0696009 , 0.06842582, 0.15651304, 0.30738689]])

In [127]:
matris.mean()

0.45458513329573763

In [128]:
matris.std()

0.2898158221214854

In [129]:
matris.var() 

0.08399321075195246

In [130]:
np.median(matris)

0.4599806395199484

In [131]:
np.min(matris)

0.022296315655774057

In [132]:
np.max(matris)

0.9900030122138573